<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to List</name>
   <tag></tag>
   <elementGuidId>01cdfda6-5827-4069-8aaf-18a115b012c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wishListMainButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wishListMainButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d8651d6-2812-4774-a493-2bdc2efb7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wishListMainButton</value>
      <webElementGuid>1ad1bb06-b5c0-4af4-a640-8e727164f795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-groupfirst a-spacing-none a-button-base</value>
      <webElementGuid>4f7e7119-75e5-43cc-acba-3a7e94732a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dd8d0e92-144f-447e-8227-309cf3cb16c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d8bfbad3-fee1-4c51-8fb0-aef7001a6df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4bc0399-a833-483f-aca4-6933f8c85755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to List </value>
      <webElementGuid>be7291d8-5b6a-4108-86e1-b2053557730c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wishListMainButton&quot;)</value>
      <webElementGuid>99a81d83-9e5a-486d-93c9-ab9a5e5adb04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wishListMainButton']</value>
      <webElementGuid>b8bcfa5e-7cdb-4943-83bf-2710b79e237a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-to-wishlist-button-group']/span</value>
      <webElementGuid>89c8c6a4-bf71-441f-b054-a0d48faa2a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div/div/span</value>
      <webElementGuid>930fde05-b51c-4b70-b0dd-febf1559b3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wishListMainButton' and (text() = ' Add to List ' or . = ' Add to List ')]</value>
      <webElementGuid>4b8cde6d-1a4a-4c1f-ac38-0cf66791bda8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
