<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.one-click-order.x</name>
   <tag></tag>
   <elementGuidId>4e89eafe-6874-4eb8-ad3f-3e1f5523f0a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#one-click-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='one-click-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8d5041e-2315-4688-b5bf-ecdf9c36b9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>one-click-button</value>
      <webElementGuid>e0c7faed-4ae2-430b-bac3-d2344c32e390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.one-click-order.x</value>
      <webElementGuid>8a62a713-d065-4fe2-91a5-e4b9212a7245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>e3d2ab0f-ed81-435f-84b4-b51373244158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>023dfc46-4b65-4ab7-9447-0b0fd0da5506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buy now with 1-Click</value>
      <webElementGuid>3c87cf58-9821-49ce-827a-8cf4877e357f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>checkoutButtonId-announce</value>
      <webElementGuid>8d06b424-92e0-41b3-8e6c-7ae77ec799e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-click-button&quot;)</value>
      <webElementGuid>18e82aa1-f1ef-4b4f-949f-aca385c44766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='one-click-button']</value>
      <webElementGuid>85f2a369-f90b-415c-a063-b9d15ca221c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='checkoutButtonId']/span/input</value>
      <webElementGuid>0f05aca8-ecf5-415c-84ee-1beb11771325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>65ab25f5-d2d1-4cce-99e0-715c8665db39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'one-click-button' and @name = 'submit.one-click-order.x' and @type = 'submit']</value>
      <webElementGuid>7d7b9cc0-336a-4123-9e5b-f68331fd9f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
