<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>1eedd294-f2fc-4fc9-bbd5-b9d35de1c756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-searchbox-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='header-searchbox-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6f3cfb7-8c35-4877-9892-72b0edbe81a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gnav-searchbox-button</value>
      <webElementGuid>9710c385-d7a8-4482-86b0-18582e1a1838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-searchbox-button</value>
      <webElementGuid>3a0ec498-563c-4e5c-882d-d1ac812eb27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e841917d-77a2-4751-9b0e-1c32247a8e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>dcda2c52-dc9d-4c08-a9d4-fa93ce33acf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-searchbox-button&quot;)</value>
      <webElementGuid>26afe3c7-751c-4ca8-afb0-af7ded5c9e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='header-searchbox-button']</value>
      <webElementGuid>79909e75-efc8-47e4-a00f-5430951f58b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='header-searchbox-form']/fieldset/div/div[2]/button</value>
      <webElementGuid>05225116-13f7-4d51-91b9-ac0b4236ab7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>be047b1f-098a-49cd-bf15-103445779faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'header-searchbox-button' and @type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>1a6bc485-cb57-485f-ae69-1baebef00507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
