<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kn</name>
   <tag></tag>
   <elementGuidId>231ef395-610e-484c-b3dc-52390400bc67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-searchbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='header-searchbox-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1da1d7b6-2e9d-44ce-a2a5-9b8396b6a4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>71098538-8a24-4312-ac6b-65abcab23787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0198698-3e40-44f7-ad4b-47f86efe873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>6528768e-db0a-48df-b92d-1b1c2d17844c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-header-searchbox-input</value>
      <webElementGuid>17a0807f-46fd-462b-9d9a-d225ee11350f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gnav-searchbox-input</value>
      <webElementGuid>cfb6aa3e-6433-4be6-b4ba-2685a3009614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-searchbox-input</value>
      <webElementGuid>d6854998-03c5-4ba7-812b-482db3ea1e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kn</value>
      <webElementGuid>9d8f6bf0-a320-4b70-b915-b4c513f09e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter keyword, title, author or ISBN</value>
      <webElementGuid>4180ec99-8f1b-4200-9908-65e0264b9f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter keyword, title, author or ISBN</value>
      <webElementGuid>ffa2cb31-b8bf-4b3b-b7da-3baf5cc404c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2265a6f-2b64-4a0b-b915-8fbe3d2ebd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>h</value>
      <webElementGuid>2728f231-6b97-456e-8a4a-5ebcf31a17a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-searchbox-input&quot;)</value>
      <webElementGuid>0dffa3b6-2a4d-47e7-b50a-21ece88e1d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='header-searchbox-input']</value>
      <webElementGuid>7ce1d9a0-d15c-43c5-9ba9-7aff74067bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='header-searchbox-form']/fieldset/div/div/div/div/div/input</value>
      <webElementGuid>e8c52bc9-3d8d-413b-8c3c-483638aa4c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>39db01e3-508b-4522-b29e-87b618a36be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'header-searchbox-input' and @name = 'kn' and @placeholder = 'Enter keyword, title, author or ISBN']</value>
      <webElementGuid>1c76359a-6cd7-45c1-b2de-5756cd0955ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
