<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Select_By_Value_And_Label_Validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ca4a12fb-2052-4b1b-b0e7-431948615e18</testSuiteGuid>
   <testCaseLink>
      <guid>82fb700f-c183-4acf-b1bf-ed3e9643372d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/009_TC_AMAZON_ValidateSelectByLabelButton</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbc11194-7b44-4781-b37e-6e171df0cf94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1e6efe9-2fef-415d-a4b2-862ffb6929bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5473b256-fe44-4738-9667-77359dbdaaeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/010_TC_AMAZON_ValidateSelectByValueButton</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f356ace-e6ec-4349-bbef-3c508c91f57d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f0664fb-00a4-4321-a941-64931dae261f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
